### PR TITLE
Match WIP (QUI-11)

### PR DESCRIPTION
**Pull request by boehs**
~~I haven't worked on this for a bit so I'm just pring what I have. I will get back around to it.~~ ok so apparently this is how you end procrastination 

- [x] Match controller
- [x] Match UI
- [x] Sync view to controller
- [x] Validate drops
- [x] Scatter on invalid
  - [x] Fade on correct
- [x] End screen
- [x] Progress sidebar
- [x] Leaderboard Component
  - [x] Backend
    - [ ] Sync to backend
    - [ ] Hydrate lb

Also, there's a hack where

1. ~~Card sizes are hardcoded~~
2. ~~Window size is hardcoded~~

Here's a little vid of what I have

~~https://github.com/miapolis/quizlet.cc/assets/51836263/6d931d7c-ca2b-4891-a99f-e746938c6a4b~~

https://github.com/miapolis/quizlet.cc/assets/51836263/07c9a72e-efbc-4fff-b55a-3b3ebee4f618

Some implementation details:

1. There's a currently unused framework to mark rounds as ineligible for leaderboards. This is so settings can be introduced like study starred, ect

### CODE REVIEW

**Comment by boehs** [comment]
Oh also it performs fine I think but also I have no clue what I'm doing react is terrible so like

**Comment by miapolis** [comment]
Overall, looks like a great start just make sure you're running the formatter. Good idea to mark rounds as ineligible for leaderboards if it is customized somehow, I didn't think of that.

Also, just looking at the video, if you haven't done this already make sure that the bottom border changes color as well when the term is completed or incorrect.

**Comment by boehs** [comment]
> Also, just looking at the video, if you haven't done this already make sure that the bottom border changes color as well when the term is completed or incorrect.

Just did in a terrible way

**Comment by uncenter** [comment]
> > Also, just looking at the video, if you haven't done this already make sure that the bottom border changes color as well when the term is completed or incorrect.
> 
> 
> 
> Just did in a terrible way

oh...

**Comment by miapolis** [comment]
@boehs I refactored a ton and the build is now passing with linter enabled. There's still the bug with random pairs not reacting every once in a while, look more into that.

**Comment by boehs** [comment]
Can you authorise CI

**Comment by miapolis** [comment]
> Can you authorise CI

I'll merge to staging tomorrow probably, it'll take a bit to set up and you don't have access to that env yet anyway.

**Comment by boehs** [comment]
There still is no leaderboards. When me and @miapolis were playing, there were some odd one off bugs, but I suspect those are HMR state – I have not encountered them since. I fixed the last big one in [0ae585f](https://github.com/miapolis/quizlet.cc/pull/98/commits/0ae585fedbb6c67dc4b9e71d3b565de903f1b671)

**Comment by boehs** [comment]
image

There was a podium which I think is cute but it just won't work well here.

```ts
import { Grid, Heading, Stack } from "@chakra-ui/react"

export const Podium = () => {
    return <Grid templateColumns="1fr 1fr 1fr" height={"200px"} alignItems="end">
        <Stack h="75%" bg={"gray.400"} borderTopLeftRadius="2xl" borderBottomLeftRadius="2xl" alignItems="center">
            <Heading size="2xl">2nd</Heading>
        </Stack>
        <Stack h="100%" bg={"yellow.300"} borderTopLeftRadius="2xl" borderTopRightRadius="2xl" alignItems="center">
            <Heading size="3xl">1st</Heading>
        </Stack>
        <Stack h="50%" bg={"orange.300"} borderTopRightRadius="2xl" borderBottomRightRadius="2xl" alignItems="center">
            <Heading size="xl">3rd</Heading>
        </Stack>
    </Grid>
}
```

**Comment by miapolis** [comment]
Still a few issues. Overall, match experience and dragging seems to be basically perfected. There is one bug however and that the controller assumes that there needs to be 6 pairs matched for the round to be completed. If there are less than 6, the round keeps going while there is nothing to do.

image

**Comment by miapolis** [comment]
> image
> There was a podium which I think is cute but it just won't work well here.
> 
> ```tsx
> import { Grid, Heading, Stack } from "@chakra-ui/react"
> 
> export const Podium = () => {
>     return <Grid templateColumns="1fr 1fr 1fr" height={"200px"} alignItems="end">
>         <Stack h="75%" bg={"gray.400"} borderTopLeftRadius="2xl" borderBottomLeftRadius="2xl" alignItems="center">
>             <Heading size="2xl">2nd</Heading>
>         </Stack>
>         <Stack h="100%" bg={"yellow.300"} borderTopLeftRadius="2xl" borderTopRightRadius="2xl" alignItems="center">
>             <Heading size="3xl">1st</Heading>
>         </Stack>
>         <Stack h="50%" bg={"orange.300"} borderTopRightRadius="2xl" borderBottomRightRadius="2xl" alignItems="center">
>             <Heading size="xl">3rd</Heading>
>         </Stack>
>     </Grid>
> }
> ```
> 
> edit: i'm going to bed this is safe to merge I have some stuff locally that isn't ready but leaderboards are completely isolated codepath-wise. For tomorrow I also need to create leaderboards for sets if they don't already exist, and do leaderboard hydration. It's like 10 minutes of work away (famous last words)

I would consider implementing a podium in the future but for now let's just keep it to a list with the top three finishers bolded perhaps.

**Comment by miapolis** [comment]
Also, another issue, you can see that the time displayed in the modal will occasionally be off by a decisecond from the actual time displayed during the round. I'm not sure which one is more accurate, just make sure they're the same value.
image

**Comment by miapolis** [comment]
One last thing, perhaps it's preferable to only scatter the card that was dragged on top instead of both (or however many were intersected). This will create less explosions on overlaps and looks cleaner overall. It's how it's done on Quizlet.com, but something we could do differently if we wanted to.

**Comment by uncenter** [comment]
> One last thing, perhaps it's preferable to only scatter the card that was dragged on top instead of both (or however many were intersected). This will create less explosions on overlaps and looks cleaner overall. It's how it's done on Quizlet.com, but something we could do differently if we wanted to.

Totally agree. On Quizlet.com (see attachment), it only scatters the card dragged/moved/on top. It seems like they figure out an empty area of the screen to scatter the card back to which makes it look nice and keep the cards visible without overlap.

https://github.com/miapolis/quizlet.cc/assets/47499684/fa760379-5e26-467f-b711-c0576b8cbf4d

One last little thing for me - the timer box in the corner should be shrunk quite a bit, it looks a little awkward!

**Comment by boehs** [comment]
Feedback sum

- [x] controller assumes that there needs to be 6 pairs matched for the round to be completed.
- [ ] Time displayed in the modal will occasionally be off by a decisecond from the actual time displayed during the round
- [x] only scatter the card that was dragged on top instead of both
- [ ] scatter the card back to which makes it look nice and keep the cards visible without overlap.
- [x] the timer box in the corner should be shrunk

- [ ] I also discovered a bug that was introduced at some point where larger cards (<1 line) have a bounding box that's too small

**Comment by boehs** [comment]
the decisecond issue should hopefully (like 99% chance) be fixed in 2d10d24, but given the nature of the bug it's hard to verify

**Comment by boehs** [comment]
the overlap issue has been fixed (by just picking spots until one works out. Should be fine performance wise. We have 

https://github.com/miapolis/quizlet.cc/assets/51836263/a88c5f09-799f-445c-8505-90339bdace2f

Bigger issues

**Comment by boehs** [comment]
Should the timer wait 0.5 seconds before starting? (the animation where cards move in)

**Comment by boehs** [comment]
Actually here's an interesting one: I was curious if you could match while cards are moving. Turns out, you can grab cards in motion, but if you successfully do so the bounding box calculations are broken for that card thereafter.

I propose

1. Disabling pointerevents for 0.5 seconds on cards in motion (hacky fix)
2. Delaying timer start for 0.5 seconds

*Alternatively* we could hunt down this bug and make it so nerds with either

1. A 1000hZ monitor
2. Like a 1992 IBM thinkpad or smth

can match cards while still in motion

**Comment by boehs** [comment]
I ended up implementing the proposed solution in d018727. Another thing: currently the presented score is a little kind. A time of `9.998` will be displayed as `9.9` instead of `10.0`. This number could be rounded, or it could continue to be kind.

**Comment by boehs** [comment]
> I ended up implementing the proposed solution in

feels a little off tbh. In the future we can mess with reducing the offsets to be somewhere between. It's a one line change.

image

**Comment by boehs** [comment]
Unless there's more critique, this is ready, minus leaderboards which are mostly done but not linked up yet, but merge without leaderboards.

**Comment by boehs** [comment]
Oops, I realized in small enough browser windows it will never load because there's just not enough free space to find empty. I'm going to add a timeout of 100

**Comment by boehs** [comment]
https://github.com/miapolis/quizlet.cc/assets/51836263/07a68a56-e7d7-4178-b44f-ed6adb0677eb

Updated video

**Comment by miapolis** [comment]
Much better! A few things however: the very first time Match is opened, there needs to be a modal with a start button so that the timer doesn't start immediately. There's also another bug where the New Match button restarts the round but new cards don't spawn in. Fix these two things and I think we're ready to merge into staging, and after leaderboard and backend work is done I'll push to prod.

image

**Comment by miapolis** [comment]
@boehs I ran prettier and moved `GridStat` into its own file. I read your comment about using refs to keep track of delayed state and it's not uncommon at all in React—I think I already do that quite a lot in this codebase already

**Comment by miapolis** [comment]
I also just realized, I know what looks off: every card is the same width, even if it's only a few characters. It'll be a little more involved to handle varying widths for cards but I think you'll be fine, the current fixed width should instead be the max width. For staging here are the last three things:

- [ ] Start modal when Match is clicked from the main set page (so timer doesn't start immediately) - on reload it's fine if it starts right away
- [ ] Fix 'New Match' button not spawning in new cards
- [ ] Cards take up the min width they need to occupy, current width becomes the max width instead

**Comment by boehs** [comment]
>  Fix 'New Match' button not spawning in new cards

Ugh when did this happen

**Comment by boehs** [comment]
I can't check your boxes so here they are again!

- [ ] Start modal when Match is clicked from the main set page (so timer doesn't start immediately) - on reload it's fine if it starts right away
- [ ] Fix 'New Match' button not spawning in new cards
- [ ] Cards take up the min width they need to occupy, current width becomes the max width instead

**Comment by boehs** [comment]
Ok ready for review part 3!

Eventually the match dialog should show a short video explaining match, like this

https://github.com/miapolis/quizlet.cc/assets/51836263/ee64f668-2d71-4b14-bac1-88a68ca9a2c1

and <Enter> should start a new game, but it's good for now imo

**Comment by miapolis** [comment]
@boehs I fixed a bunch of things, window resizing handling now works as well. I've noticed a few bugs however relating to z indices once again, especially with sets with fewer than 6 terms... a lot of cards don't seem to have the highest order z-index when being dragged in these scenarios

**Comment by boehs** [comment]
LGTM, resize handling is great. Debugging the z-index stuff is difficult and I'm struggling to reproduce. I'm tempted to chalk it up to HMR

**Pull request merged**
